In [1]:
import numpy as np

In [2]:
attr = np.loadtxt("attribute_representation.txt")

In [8]:
(attr>0).astype(int)

array([[1, 1, 1, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 1, 0, 0],
       [1, 1, 0, ..., 1, 0, 0]])

In [11]:
CLASS_NAME = ["aeroplane","bicycle","bird","boat","bottle",
             "bus","car","cat","chair","cow",
             "diningtable","dog","horse","motorbike","person",
             "pottedplant","sheep","sofa","train","tvmonitor",
             "donkey","monkey","goat","wolf","jetski",
             "zebra","centaur","mug","statue","building",
             "bag","carriage"]

In [14]:
CLASS_NAME.index("bicycle")

1

In [15]:
attr = np.load("attribute-representation-split1.npy")

In [16]:
attr

array([[ 51.,  79.,  17., ..., 105.,   0.,   0.],
       [  0.,   0.,   0., ...,  77.,   0.,   0.],
       [ 80.,  92.,   9., ...,  42.,   0.,   0.],
       ...,
       [  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ..., 100.,   0.,   0.],
       [ 35.,  76.,  10., ...,   0.,   0.,  14.]])

In [17]:
attr[-5]

array([  0.,   0.,   0.,   0.,   0., 104., 168., 211., 233.,   0.,   0.,
         0.,   0.,   0.,   0., 184., 223.,   0.,   0., 158., 135., 156.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0., 247.,   0.,   0.,   0.,   0.,   0.])